print("What is your name?")
name=input()
print("What is your organization?")
org=input()
print("Enter your contact info")
contact=input()
print("What is your access level?")
access=input()


print("|-------------------------------------------------|")
print("| attendee : " + name.ljust(37) + "|")
print("| org : " + org.ljust(42) + "|")
print("| contact : " + contact.ljust(38) + "|")
print("| access : " + access.ljust(39) + "|")
print("| issuer : BCH Software Terminal System           |")
print("|-------------------------------------------------|")